services:
  - type: web
    name: live-relay
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SOURCE_URL
        value: https://cdn.vpplayer.tech/agmipocq/hub/D188B8A9-8433-4A86-95FB-DB6BCAEC9BFA/index.m3u8
      - key: RTMP_URL
        value: rtmp://ingest.example.com/live
      - key: STREAM_KEY
        value: YOUR_STREAM_KEY
      - key: REFERER
        value: https://host.vpplayer.tech/player/ptkzusga/vjsoalga.html
      # - key: SELF_URL
      #   value: https://live-relay.onrender.com/health